version: '3.1'

services:

  db:
    image: postgres
    container_name: postgres
      # restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
